FROM rabbitmq:3.12-management

# 플러그인 다운로드 및 설치
RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez
RUN mv rabbitmq_delayed_message_exchange-3.12.0.ez /plugins/
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange